kind: LimitRange
apiVersion: v1
metadata:
  name: mem-limit-range
  namespace: customer01
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 500Mi
    defaultRequest:
      cpu: 1m
      memory: 1Mi
