kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  #  namespace: customer01
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        deployment: minio
    spec:
      containers:
        - name: minio
          command:
            - /bin/bash
            - '-c'
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: M!nioOhYeah
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          image: minio/minio
          args:
            - 'minio server /data --console-address :9090'
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  #  namespace: customer01
spec:
  type: ClusterIP
  ports:
  - name: minio      
    port: 9000
  selector:
    app: minio
---    
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  #  namespace: customer01
spec:
  type: ClusterIP
  ports: 
  - name: minio-ui
    port: 9090
  selector:
    app: minio
